server:
  port: 8087

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: pickup-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "com.flipkart.pickup.event"
        spring.json.value.default.type: "com.flipkart.pickup.event.OrderCreatedEvent"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka